routes/web.php
<?php

use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LupaPasswordController;
use App\Http\Controllers\LogoutController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('beranda');
});

Route::controller(RegisterController::class)->name('register.')->prefix('register')->group(function()
{
    Route::get('/','formRegister')->name('form-register');
    Route::post('/simpan-register','simpanRegister')->name('simpan-register');
});
Route::controller(LoginController::class)->name('login.')->prefix('login')->group(function()
{
    Route::get('/','formLogin')->name('form-login');
    Route::post('/proses-login','ProsesLogin')->name('proses-login');
    
});
Route::controller(AdminController::class)->name('admin.')->middleware('CekLogin:admin')->prefix('admin')->group(function()
{
    Route::get('/','BerandaAdmin')->name('beranda');
    Route::get('/list','list')->name('list');
    Route::get('/buat', 'create')->name('create');
    Route::post('/simpan', 'store')->name('simpan');
    Route::get('/edit/{id}', 'edit')->name('edit');
    Route::post('/update/{id}', 'update')->name('update');
    Route::get('/hapus/{id}', 'hapus')->name('hapus');
});
Route::controller(UserController::class)->name('user.')->middleware('CekLogin:user')->prefix('user')->group(function()
{
    Route::get('/','BerandaUser')->name('beranda');    
    Route::get('/aboutus', 'aboutus')->name('aboutus');
    Route::get('/detail/{id}', 'detail')->name('detail');
});
Route::controller(LupaPasswordController::class)->name('forgot.')->prefix('forgot')->group(function()
{
    Route::get('/', 'formLupaPassword')->name('form-forgot');
    Route::post('/proses', 'prosesLupaPassword')->name('proses');
    Route::get('/reset-password/{token}', 'resetPassword')->name('reset-password');
    Route::post('/proses-reset', 'prosesResetPassword')->name('proses-reset');
});

Route::controller(LogoutController::class)->name('logout.')->prefix('logout')->group(function()
{
    Route::get('/','ProsesLogout')->name('proses-logout');
    
});

resources/views/admin/beranda.blade.php
@extends('templates.default_admin')

@section('content')
    <p class="text-danger">
        @if (session('error'))
            {{ session('error') }}
        @endif
    </p>
    <div class="page-header d-print-none">
        <div class="container-xl">
            <div class="row g-2 align-items-center">
                <div class="col">
                    <!-- Page pre-title -->
                    <h2 class="page-pretitle">
                        Halo {{ Auth::user()->name }}, Selamat Datang di Beranda Admin
                    </h2>
                    <h2 class="page-title">
                        Tersedia {{ $listings->count() }} Website
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="page-body">
        <div class="container-xl ">
            <div class="row row-deck row-cards ">
                @foreach ($listings as $key => $listing)
                    <div class="col-sm-4 col-lg-4 gap-3">
                        <div class="card card-sm">
                            <a href="#" class="d-block">
                                <img src="/storage/{{ $listing->logo }}" class="card-img-top"
                                    style="width:500px; height:250px;"></a>
                            <div class="card-body">
                                <div>
                                    <div>
                                        <div>{{ $listing->title }}</div>
                                        <div><b>Harga= Rp.{{ $listing->location }}</b></div>
                                    </div>
                                    <div class="page-header d-print-none">
                                        <div class="container-xl">
                                            <div class="row g-2 align-items-center">
                                                <div class="col-auto ms-auto d-print-none">
                                                    <div class="d-flex align-items-center">
                                                        <a href="#" class="text-muted">
                                                            <!-- Download SVG icon from http://tabler-icons.io/i/eye -->
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon"
                                                                width="24" height="24" viewBox="0 0 24 24"
                                                                stroke-width="2" stroke="currentColor" fill="none"
                                                                stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none">
                                                                </path>
                                                                <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                                                                <path
                                                                    d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6">
                                                                </path>
                                                            </svg>
                                                            {{ $listing->views }}
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/admin/create.blade.php
@extends('templates.default_admin')
@section('content')
    @php
        $title = 'Create Data - Admin';
    @endphp

    <div class="mb-4" style="margin-top: 20px">
        <h1 class="text-2xl font-medium text-black title-font">
            Tambahkan Website
        </h1>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row row-cards">
                <div class="col-12">
                    @if ($errors->any())
                        <div class="mb-4 p-4 bg-red-200 text-red-800">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('admin.simpan') }}" id="payment_form" method="post" enctype="multipart/form-data"
                        class="card">
                        @csrf
                        <div class="card-body">
                            <form class="card">
                                <div class="card-body">
                                    <div class="row row-cards">
                                        <div class="col-md-12">
                                            <div class="mb-3">
                                                <label class="form-label">Jenis Website</label>
                                                <input type="text" class="form-control" id="title" name="title"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="mb-3 mb-0">
                                                <label class="form-label">Keterangan</label>
                                                <textarea rows="5" class="form-control" id="company" name="company" required></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="mb-3">
                                                <label class="form-label">Harga</label>
                                                <input type="text" class="form-control" id="location" name="location"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="mb-3">
                                            <div class="form-label">Masukkan Gambar</div>
                                            <input type="file" class="form-control" id="logo" name="logo">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-end">
                                    <button type="submit" id="form_submit" class="btn btn-primary">Posting</button>
                                </div>
                            </form>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('templates.default_admin')

@section('content')
    @php
        $title = 'Edit Data - Admin';
    @endphp
    <div class="page-body">
        <div class="container-xl">
            <div class="row row-cards">
                <div class="col-12">
                    @if ($errors->any())
                        <div class="mb-4 p-4 bg-red-200 text-red-800">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('admin.update', $listingdata->id) }}" id="payment_form" method="POST"
                        enctype="multipart/form-data" class="card">
                        @csrf
                        <div class="card-header">
                            <h4 class="card-title">Form Edit</h4>
                        </div>
                        <div class="card-body">
                            <form class="card">
                                <div class="card-body">
                                    <div class="row row-cards">
                                        <div class="col-md-12">
                                            <div class="mb-3">
                                                <label class="form-label">Jenis Website</label>
                                                <input type="text" class="form-control" id="title" name="title"
                                                    value="{{ $listingdata->title }}" required />
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="mb-3 mb-0">
                                                <label class="form-label">Keterangan</label>
                                                <textarea rows="5" class="form-control" id="company" name="company"required>{{ $listingdata->company }}</textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="mb-3">
                                                <label class="form-label">Harga</label>
                                                <input type="text" class="form-control" id="location" name="location"
                                                    value="{{ $listingdata->location }}" required />
                                            </div>
                                        </div>
                                        <div class="mb-3">
                                            <div class="form-label">Masukkan Gambar</div>
                                            <input type="file" class="form-control" id="logo"
                                                value="{{ $listingdata->logo }}" name="logo" />
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-end">
                                    <button type="submit" class="btn btn-primary" id="form_submit">Update</button>
                                </div>
                            </form>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/list.blade.php
@extends('templates.default_admin')

@section('content')
    @php
        $title = 'List data - Admin';
    @endphp

    <div class="page-header d-print-none">
        <div class="container-xl">
            <div class="row g-1 align-items-center">
                <div class="col-auto ms-auto d-print-none">
                    <div class="btn-list">
                        <a href="{{ route('admin.create') }}" class="btn btn-primary d-none d-sm-inline">
                            <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M12 5l0 14"></path>
                                <path d="M5 12l14 0"></path>
                            </svg>
                            Tambahkan Website
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">

            <div class="row row-cards">
                <div class="col-lg-13">
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-vcenter card-table">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Jenis Website</th>
                                        <th>Keterangan</th>
                                        <th>Harga</th>
                                        <th colspan="2"></th>
                                    </tr>
                                </thead>
                                @php
                                    $no = 1;
                                @endphp
                                <tbody>
                                    @foreach ($listings as $listing)
                                        <tr>
                                            <td>{{ $no++ }}</td>
                                            <td>{{ $listing->title }}</td>
                                            <td class="text-muted">{{ $listing->company }}</td>
                                            <td class="text-muted">Rp.{{ $listing->location }}</td>
                                            <td>
                                                <a href="{{ route('admin.edit', $listing->id) }}">Edit</a>
                                            </td>
                                            <td>
                                                <a href="{{ route('admin.hapus', $listing->id) }}"
                                                    onclick="return confirm('Apakah Anda Ingin Mehapus Data ini?');">Hapus</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection